/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se a API está respondendo */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Limites do serviço */
        get: operations["get_limits_api_v1_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpreta texto colado ou digitado
         * @description Separa as pessoas, normaliza os nomes e aponta vazios, inválidos e duplicados. Também usado para validar um nome digitado ou editado.
         */
        post: operations["import_text_api_v1_imports_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpreta uma planilha .xlsx ou um arquivo .csv
         * @description O corpo da requisição é o próprio arquivo (não multipart), lido em memória e descartado ao fim da requisição. Opções viajam como índices: nomes de arquivo e de aba nunca aparecem na URL.
         */
        post: operations["import_file_api_v1_imports_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Executa uma rodada
         * @description Sorteia posições na lista de participantes disponíveis com o gerador criptográfico do sistema operacional. Nenhum nome é enviado e nada é gravado.
         */
        post: operations["create_round_api_v1_rounds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera o arquivo de resultado (CSV ou XLSX)
         * @description Recebe as rodadas escolhidas e devolve o arquivo. Nada é gravado no servidor.
         */
        post: operations["create_export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Algorithm: "partial-fisher-yates/1+os-csprng" | "uniform-with-replacement/1+os-csprng";
        /** ColumnOut */
        ColumnOut: {
            /** Index */
            index: number;
            /** Letter */
            letter: string;
            /** Label */
            label: string;
            /** Samples */
            samples: string[];
            /** Filled */
            filled: number;
        };
        /** DuplicateGroupOut */
        DuplicateGroupOut: {
            /** Name */
            name: string;
            /** Count */
            count: number;
            /**
             * Rows
             * @description Primeiras linhas do grupo (até 20).
             */
            rows: number[];
        };
        /** EntryOut */
        EntryOut: {
            /**
             * Row
             * @description Linha (ou item) de origem, a partir de 1.
             */
            row: number;
            /**
             * Name
             * @description Nome normalizado, pronto para exibir.
             */
            name: string;
            /**
             * Key
             * @description Chave de duplicidade (sem acentos, maiúsculas e espaços extras).
             */
            key: string;
            /**
             * Repeat Of
             * @description Linha da primeira ocorrência, se for repetição.
             */
            repeat_of: number | null;
        };
        /**
         * ExportRequest
         * @description Dados que o navegador envia para gerar o arquivo. Nada é guardado no servidor.
         */
        ExportRequest: {
            /** Draw Name */
            draw_name: string;
            /**
             * Timezone
             * @description Fuso IANA, ex.: America/Sao_Paulo.
             */
            timezone: string;
            /** Rounds */
            rounds: components["schemas"]["ExportRoundIn"][];
        };
        /** ExportRoundIn */
        ExportRoundIn: {
            /** Number */
            number: number;
            /**
             * Drawn At
             * Format: date-time
             */
            drawn_at: string;
            /** Quantity */
            quantity: number;
            /** Allow Repeat */
            allow_repeat: boolean;
            /** Remove Winners */
            remove_winners: boolean;
            /** Total Participants */
            total_participants: number;
            /** Pool Size */
            pool_size: number;
            algorithm: components["schemas"]["Algorithm"];
            /** Winners */
            winners: components["schemas"]["ExportWinnerIn"][];
        };
        /** ExportWinnerIn */
        ExportWinnerIn: {
            /** Position */
            position: number;
            /** Name */
            name: string;
        };
        /** FieldErrorOut */
        FieldErrorOut: {
            /** Field */
            field: string;
            /** Type */
            type: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ImportPreviewOut */
        ImportPreviewOut: {
            /**
             * Source
             * @enum {string}
             */
            source: "text" | "csv" | "xlsx";
            /** Entries */
            entries: components["schemas"]["EntryOut"][];
            /**
             * Issues
             * @description Até 100 linhas com problema; total em `stats`.
             */
            issues: components["schemas"]["IssueOut"][];
            /**
             * Duplicate Groups
             * @description Até 100 grupos.
             */
            duplicate_groups: components["schemas"]["DuplicateGroupOut"][];
            stats: components["schemas"]["StatsOut"];
            /**
             * Separator
             * @description Separador usado (texto) ou delimitador (CSV).
             */
            separator: string | null;
            /** Has Header */
            has_header: boolean;
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Column */
            column: number | null;
            /** Sheets */
            sheets: components["schemas"]["SheetOut"][];
            /** Sheet */
            sheet: number | null;
            /** Max Name Length */
            max_name_length: number;
        };
        /** ImportTextRequest */
        ImportTextRequest: {
            /**
             * Text
             * @description Texto colado ou digitado.
             */
            text: string;
            /**
             * Separator
             * @description Como separar as pessoas. Em `auto`, mais de uma linha → uma por linha; senão ponto e vírgula; senão vírgula. Colunas com tab viram tabela.
             * @default auto
             * @enum {string}
             */
            separator: "auto" | "newline" | "semicolon" | "comma";
            /**
             * Header
             * @default auto
             * @enum {string}
             */
            header: "auto" | "yes" | "no";
            /** Column */
            column?: number | null;
        };
        /** IssueOut */
        IssueOut: {
            /** Row */
            row: number;
            /**
             * Code
             * @enum {string}
             */
            code: "too_long" | "cell_error";
        };
        /**
         * LimitsOut
         * @description Limites do serviço, para a interface validar antes de enviar.
         */
        LimitsOut: {
            /** Max Participants */
            max_participants: number;
            /** Max Round Quantity */
            max_round_quantity: number;
            /** Max Name Length */
            max_name_length: number;
            /** Max Draw Name Length */
            max_draw_name_length: number;
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Max Text Chars */
            max_text_chars: number;
            /** Max Export Rounds */
            max_export_rounds: number;
        };
        /**
         * ProblemOut
         * @description Erro no formato RFC 9457 (``application/problem+json``).
         */
        ProblemOut: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number | string;
            };
            /** Request Id */
            request_id?: string | null;
        };
        /** RoundOut */
        RoundOut: {
            /**
             * Positions
             * @description Posições sorteadas (a partir de 0) na lista de disponíveis, na ordem do sorteio: a primeira é o 1º vencedor.
             */
            positions: number[];
            /** Pool Size */
            pool_size: number;
            /** Quantity */
            quantity: number;
            /** Allow Repeat */
            allow_repeat: boolean;
            /**
             * Algorithm
             * @description Algoritmo e fonte de aleatoriedade usados.
             */
            algorithm: string;
            /**
             * Drawn At
             * Format: date-time
             * @description Horário oficial da rodada (relógio do servidor).
             */
            drawn_at: string;
        };
        /**
         * RoundRequest
         * @description Pedido de rodada. Nenhum nome é enviado: o servidor escolhe posições na lista de
         *     participantes disponíveis que o navegador congelou no momento do clique (ADR-018).
         */
        RoundRequest: {
            /**
             * Pool Size
             * @description Quantos participantes estão disponíveis.
             */
            pool_size: number;
            /**
             * Quantity
             * @description Quantos vencedores sortear.
             */
            quantity: number;
            /**
             * Allow Repeat
             * @description Se a mesma pessoa pode sair mais de uma vez.
             */
            allow_repeat: boolean;
        };
        /** SheetOut */
        SheetOut: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Hidden */
            hidden: boolean;
        };
        /** StatsOut */
        StatsOut: {
            /**
             * Rows
             * @description Linhas de dados lidas (sem o cabeçalho).
             */
            rows: number;
            /** Valid */
            valid: number;
            /** Empty */
            empty: number;
            /** Invalid */
            invalid: number;
            /**
             * Duplicates
             * @description Ocorrências repetidas além da primeira.
             */
            duplicates: number;
            /** Duplicate Groups */
            duplicate_groups: number;
            /**
             * Dates
             * @description Valores que eram datas: indica coluna provavelmente errada.
             */
            dates: number;
        };
        /** ValidationProblemOut */
        ValidationProblemOut: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number | string;
            };
            /** Request Id */
            request_id?: string | null;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FieldErrorOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_limits_api_v1_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsOut"];
                };
            };
        };
    };
    import_text_api_v1_imports_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewOut"];
                };
            };
            /** @description Dados ou arquivo inválidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblemOut"];
                };
            };
            /** @description Muitas requisições. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    import_file_api_v1_imports_file_post: {
        parameters: {
            query?: {
                format?: ("xlsx" | "csv") | null;
                sheet?: number | null;
                column?: number | null;
                header?: "auto" | "yes" | "no";
                delimiter?: "auto" | "semicolon" | "comma" | "tab" | "none";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewOut"];
                };
            };
            /** @description Arquivo grande demais. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Formato não suportado. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Dados ou arquivo inválidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblemOut"];
                };
            };
            /** @description Muitas requisições. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    create_round_api_v1_rounds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundOut"];
                };
            };
            /** @description Pedido inválido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblemOut"];
                };
            };
            /** @description Muitas requisições. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    create_export_api_v1_exports_post: {
        parameters: {
            query?: {
                format?: "csv" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Arquivo gerado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Dados inválidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblemOut"];
                };
            };
            /** @description Muitas requisições. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
}
